config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  resources :users
  resources :questions

  resources :sessions, :only => [:new, :create, :destroy]

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
end

app/models/question.rb
class Question < ActiveRecord::Base

  default_scope {order('created_at DESC')}
  validates_presence_of :option_one, :option_two
  has_and_belongs_to_many :users

  has_attached_file :image_one, styles: { medium: "250x200>", thumb: "100x100>" }, default_url: "/images/:style/tiger.jpg"
  validates_attachment_content_type :image_one, content_type: /\Aimage\/.*\Z/

  has_attached_file :image_two, styles: { medium: "250x200>", thumb: "100x100>" }, default_url: "/images/:style/tiger.jpg"
  validates_attachment_content_type :image_two, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :email
  validates_presence_of :username
  has_and_belongs_to_many :questions

  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all

  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path
    else
      flash[:notice] = "What are you doing"
      render :new
    end
  end

  def update
    @question = Question.find(params[:id])

    if params[:which] == @question.option_one
      @option = 'one'
      @option_string = 'points_one'
      @question.points_one += 1
      @points = @question.points_one
    elsif  params[:which] == @question.option_two
      @option = 'two'
      @question.points_two += 1
      @points = @question.points_two
    else
    end

    if @question.save
      respond_to do |format|
        format.html {redirect_to questions_path}
        format.js
      end
    else
    redirect_to root_path
    end



  end

  private
  def question_params
    params.require(:question).permit(:option_one, :option_two, :image_one, :image_two)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "Logged in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "Invalid Email or Password"
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Log out successful"
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Nailed it!!"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end


private

  def user_params
    params.require(:user).permit(:password, :email, :username, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WouldYouRather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-custom">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to (image_tag 'trimet.png'), root_path, class: 'navbar-brand' %>
      </div>

      <div>
        <ul class="nav navbar-nav">
          <li><a href="#">Categories</a></li>
        </ul>
        <div class="center-navbar">Trimet Troubles</div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Pose A Questsh', new_question_path %></li>
          <%= yield(:navbar) %>
        </ul>
      </div>
    </div>
  </nav>

<div class='container body-wrapper'>
  <%= flash[:notice]%>
  <%= flash[:alert]%>
  <%= yield %>

</div>

</body>
</html>

app/views/questions/_graph_tile.html.erb
<% @chart1 = LazyHighCharts::HighChart.new('graph') do |f|
  f.chart({:defaultSeriesType=>"pie", :margin=> [50, 0, 0, 0], :height => 150})
  f.title({:text => "Votes"})
  f.series({
    :type => "pie",
    :name => "2008",
    :size => "150%",
    :innerSize => "40%",
    :startAngle => -90,
    :endAngle => 90,
    :data => [{ :name => "#{@question.option_one}", :y => @question.points_one, :color => "#2677bb" },{ :name => "#{@question.option_two}", :y => @question.points_two, :color => "#f67944" }],
    :dataLabels=> { :enabled => false }
  }
  )
end %>


<%= high_chart("stuff#{@question.id}", @chart1) %>

app/views/questions/_question_tile.html.erb
<div class='question-tile'>
  <div class='row'>
    <h2>Would you rather...?</h2>
    <div class='col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-12 col-xs-12'>
      <%= link_to question_path(question, which: question.option_one), {method: :patch, remote: true, class: "#{question.id}-link" } do %>
        <div class='col-lg-5 col-md-5 col-sm-5 col-xs-5 side-by-side-container'>
          <%= image_tag question.image_one.url(:medium) %>
          <br>
          <h5 class='text-center'>
            <%= question.option_one %>
            <span id='<%= question.id %>-option-one-points'><%= question.points_one %></span>
          </h5>

        </div>
      <% end %>
      <div class='col-lg-2 col-md-2 col-sm-2 col-xs-2 '>
        <div class='text-center question-meta' id='<%= question.id %>-question-meta'>
          <h4><span class='glyphicon glyphicon-menu-left'></span> OR
            <span class='glyphicon glyphicon-menu-right'></span></h4>



        </div>
      </div>
      <%= link_to question_path(question, which: question.option_two), method: 'patch', remote: true, class: "#{question.id}-link" do %>
        <div class='col-lg-5 col-md-5 col-sm-5 col-xs-5 side-by-side-container'>
          <%= image_tag question.image_two.url(:medium) %>
          <br>
          <h5 class='text-center'>
            <%= question.option_two %>
            <span id='<%= question.id %>-option-two-points'><%= question.points_two %></span>
          </h5>

        </div>
      <% end %>

    </div>

  </div>

</div>

app/views/questions/index.html.erb
<% content_for(:navbar) do %>
  <% if current_user %>
   <li><%= link_to "Log Out #{current_user.email}", log_out_path %></li>
   <% else %>
    <li><%= link_to 'Log In', log_in_path %></li>
    <li><%= link_to 'Sign Up', new_user_path %></li>
  <% end %>
<% end %>



<% if @questions.any? %>
  <% @questions.each do |question| %>
    <%= render "question_tile", question: question %>
  <% end %>
<% else %>
no images
<% end %>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
<div class='row'>
  <div class='question-tile-title text-center'>
    <h2>Would You Rather</h2>
  </div>
  <br>
  <div class='col-md-4 col-md-offset-1'>
    <div class='form-group'>
      <%= f.label 'Catastrophe One' %>
      <%= f.text_field :option_one, class: 'form-control' %>
      <br>
      <%= f.file_field :image_one, class: 'form-control' %>

    </div>

  </div>
  <div class='col-md-2'>
    <div class='text-center'>
      <h4><span class='glyphicon glyphicon-menu-left'></span> OR
        <span class='glyphicon glyphicon-menu-right'></span></h4>
    </div>
  </div>
  <div class='col-md-4'>
    <div class='form-group'>
      <%= f.label 'Disaster Two' %>
      <%= f.text_field :option_two, class: 'form-control'  %>
      <br>
      <%= f.file_field :image_two, class: 'form-control'  %>

    </div>

  </div>

</div>
<div class='text-center'>
  <%= f.submit "Questsch it!", class: 'btn btn-primary btn-sm' %>
</div>

<% end %>

app/views/questions/update.js.erb
$(function() {
  $('#<%= @question.id %>-option-<%= @option %>-points').text("<%= @points %>");
  $('#<%= @question.id %>-option-<%= @option %>-points').parents('.side-by-side-container').addClass('selected-<%= @option %>');
  $(".<%= @question.id %>-link").addClass('unclickable');
  $('#<%= @question.id %>-question-meta').append('<%= j render ("graph_tile") %>')
});

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class ="container">
  <%= form_for @user, :html => {:class => "form-horizontal center"} do |f| %>

    <div class="form-group">
      <%= f.label :email, "E-Mail", class: "control-label" %>
        <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :username, "Pick a Username", class: "control-label" %>
        <%= f.text_field :username, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password, "Password", class: "control-label" %>
        <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, "Confirm Password", class: "control-label" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <%= f.submit "Submit", class: "btn btn-default" %>
  <% end %>
</div>